### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by ohenrik** [philipperemy/lead-lag#5]
Hi

I'm trying to install and use this package, however it seems like there is something wrong.

Cython is correctly installed and i installing requirements worked fine. 

I am on Ubuntu 18.04 running Python 3.7.2 and I'm using virtualenv to isolate the installation. 

Bellow is the error resulting from running `python -c "import lead_lag; print('success')"`:

```python
(lead_lag_test) ➜  lead-lag git:(master) ✗ python -c "import lead_lag; print('success')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ohenrik/Projects/lead_lag_test/lead-lag/lead_lag/__init__.py", line 1, in <module>
    from lead_lag.lead_lag import *
  File "/home/ohenrik/Projects/lead_lag_test/lead-lag/lead_lag/lead_lag.py", line 11, in <module>
    from lead_lag.contrast import CrossCorrelationHY
  File "/home/ohenrik/Projects/lead_lag_test/lead-lag/lead_lag/contrast.py", line 6, in <module>
    from lead_lag.lead_lag_impl import shifted_modified_hy_estimator
ModuleNotFoundError: No module named 'lead_lag.lead_lag_impl'
```

I have also tried to compile the cython code manually by running: `python setup.py build_ext --inplace`. This does not work ether.

Are there any other C packages that might be required?

If everything is working fine on your machine, could you please try and create a new virtualenv and installing the package there and see if that creates any errors.

**Comment by philipperemy** [comment]
Hey,

Are you running `python -c "import lead_lag; print('success')"` inside the lead_lag project? If so, it's not going to work. Go to `/tmp/` or anywhere else and run it again. It should work.

> Are there any other C packages that might be required?
There's no other C packages.

> If everything is working fine on your machine.
Yes it's running fine. I created a new virtualenv, installed the package and ran the command. Here is the full output:

```
[8:51:40 - 19-03-28] /tmp % git clone git@github.com:philipperemy/lead-lag.git && cd lead-lag
Cloning into 'lead-lag'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 394 (delta 16), reused 0 (delta 0), pack-reused 367
Receiving objects: 100% (394/394), 880.37 KiB | 1019.00 KiB/s, done.
Resolving deltas: 100% (217/217), done.
```


```
[8:52:01 - 19-03-28] /tmp/lead-lag % source venv3.6/bin/activate
```

```
(venv3.6) [8:53:24 - 19-03-28] /tmp/lead-lag % pip list | grep lead-lag
```
=> nothing.

```
(venv3.6) [8:52:02 - 19-03-28] /tmp/lead-lag % make
make install
pip install cython
Collecting cython
  Using cached https://files.pythonhosted.org/packages/d0/27/d7e796420dd1c69135ccf1362cd8ecf61a09db990a8335d65cd715b275b6/Cython-0.29.6-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: cython
Successfully installed cython-0.29.6
pip install . --upgrade
Processing /private/tmp/lead-lag
Collecting pandas>=0.22.0 (from lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/2a/67/0a59cb257c72bb837575ca0ddf5f0fe2a482e98209b7a1bed8cde68ddb46/pandas-0.24.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.15.0 (from lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/93/0e/30aaa357c3065957344b240482818eef31d4080f73dfa5f1ef7dcd8744d2/numpy-1.16.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tqdm>=4.19.2 (from lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
Collecting matplotlib>=2.2.2 (from lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/82/7e/184d995d711e3401722769cd6982b46d42aee14a82ba54a3a79425f939c9/matplotlib-3.0.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pytz>=2011k (from pandas>=0.22.0->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.0 (from pandas>=0.22.0->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.2.2->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=2.2.2->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/fb/96/619db9bf08f652790fa9f3c3884a67dc43da4bdaa185a5aa2117eb4651e1/kiwisolver-1.0.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=2.2.2->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.5.0->pandas>=0.22.0->lead-lag==1.4)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools in ./venv3.6/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2.2->lead-lag==1.4) (40.8.0)
Building wheels for collected packages: lead-lag
  Building wheel for lead-lag (setup.py) ... done
  Stored in directory: /Users/premy/Library/Caches/pip/wheels/e1/a2/20/f95adb07697410731e7b5649c0ec30a2134355a5d4a3accca9
Successfully built lead-lag
Installing collected packages: pytz, numpy, six, python-dateutil, pandas, tqdm, pyparsing, kiwisolver, cycler, matplotlib, lead-lag
Successfully installed cycler-0.10.0 kiwisolver-1.0.1 lead-lag-1.4 matplotlib-3.0.3 numpy-1.16.2 pandas-0.24.2 pyparsing-2.3.1 python-dateutil-2.8.0 pytz-2018.9 six-1.12.0 tqdm-4.31.1
```

```
(venv3.6) [8:52:38 - 19-03-28] /tmp/lead-lag % pip list | grep lead-lag
lead-lag        1.4
```

```
(venv3.6) [8:52:54 - 19-03-28] /tmp/lead-lag % cd ~ && python -c "import lead_lag; print('success')" && cd ~-
success
```

Let me know how it works on your end.

**Comment by philipperemy** [comment]
I have the same error if I run in from the lead-lag (root dir) repo directly.
```
(venv3.6) [9:00:20 - 19-03-28] /tmp/lead-lag % python -c "import lead_lag; print('success')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/lead-lag/lead_lag/__init__.py", line 1, in <module>
    from .lead_lag import *
  File "/private/tmp/lead-lag/lead_lag/lead_lag.py", line 11, in <module>
    from .contrast import CrossCorrelationHY
  File "/private/tmp/lead-lag/lead_lag/contrast.py", line 6, in <module>
    from lead_lag.lead_lag_impl import shifted_modified_hy_estimator
ModuleNotFoundError: No module named 'lead_lag.lead_lag_impl'
```

If I jump out of this repo, it works well.
```
(venv3.6) [9:00:23 - 19-03-28] /tmp/lead-lag % cd
(venv3.6) [9:00:37 - 19-03-28] /Users/premy % python -c "import lead_lag; print('success')"
success
```

**Comment by philipperemy** [comment]
Inside the repo directly, it will yield an error because we need to compile it to a `so` object. That's what `pip install` does. So if we run it inside the repo, by default the library generated by pip won't be used. Instead the sources will be used. And inside the sources, there's only the `pyx` file, and it's not enough to be able to run the code.

**Comment by ohenrik** [comment]
I see, strange that i have never encountered this problem before when building cython projects. I have previously just compiled the cython code using `python setup.py build_ext --inplace`. This allowed me to use the package directly.

So i did some digging and found this: https://stackoverflow.com/a/53356077/900271
When switching the order of the imports for Cython build i managed to correctly build the source code inside the project dir so that the package can be used directly. It might be that this is required for the package to work on windows.

I have made a pull request here: #6

**Comment by philipperemy** [comment]
That was not an easy one to spot. Thanks a lot for this detailed explanation. I'm going to review and approve the pull request!

**Comment by philipperemy** [comment]
Mergedd https://github.com/philipperemy/lead-lag/commit/3a659946982be5636e44f31d5d55600688b9b94c
